name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

#    runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: recursive

    - name: version
      run: make --version

    - name: show_var
      run: make show_var

    - name: build
      run: make

    - name: test debug
      run: make test --debug

    - name: test
      run: make test

#    - name: configure
#      run: ./configure

#    - name: Install dependencies
#      run: make

#    - name: Run check
#      run: make check

#    - name: Run distcheck
#      run: make distcheck
